# -*- coding: utf-8 -*-
"""Chatbot_CodSoft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmrVFGDLEx6SRmxPIKSKN4IvwycMJdMC
"""

import random
def chatbot_reply(user_input):
    user_input = user_input.lower()

    if "hello" in user_input or "hi" in user_input:
        return random.choice(["Hello!", "Hi there!", "Hey!"])

    elif "how are you" in user_input:
        return random.choice(["I'm good! How about you?", "I'm doing well, thanks!"])

    elif "what is your name" in user_input:
        return "I'm your simple chatbot, created by Shreeja for CodSoft Internship!"

    elif "who created you" in user_input:
        return "I was created by Shreeja as part of the CodSoft AI Internship."

    elif "tell me a joke" in user_input:
        return random.choice(["Why don’t programmers like nature? Too many bugs!",
                              "Why did the computer go to therapy? It had too many pop-ups!"])

    elif "bye" in user_input:
        return "Goodbye! Have a great day!"

    else:
        return "I'm not sure about that. Can you ask me something else?"

# Running the chatbot
print("Chatbot: Hello! Type something to chat. Type 'bye' to exit.")
while True:
    user_message = input("You: ")
    if user_message.lower() == "bye":
        print("Chatbot: Goodbye! Have a great day!")
        break
    else:
        print("Chatbot:", chatbot_reply(user_message))